spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app?useUnicode=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#base:
#  imagePath:  /opt/images/
#
#logging:
#  path: /opt/logs/send
#
rrd:
  sendUrl: https://lcl-open.creditcloud.com/open/loan-receive

base:
  imagePath:  D://opt/imgs/

logging:
  path: D://logs/send