server:
  port: 80
spring:
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jikewang.send.domain
  configuration:
     #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
     map-underscore-to-camel-case: true
     call-setters-on-nulls: true

logging:
  config: classpath:logback-spring.xml

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: true
    params: count=countSql